# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Anubhav Singh"
subtitle: "See the world through experience!!"
author:  "Anubhav Singh"
header:
 title: "Photography"
 subtitle: "by Anubhav Singh"
footer:
 name: "Hey there, I am Anubhav Singh "
 bio: "a final year computer engineering student at the SMVD University, J&K."
social_urls:
  twitter: "https://twitter.com/anubhavpulkit"
  instagram: "https://www.instagram.com/soloe_xperience/"
  linkedin: "https://www.linkedin.com/in/anubhavpulkit"
  github: "https://github.com/anubhavpulkit"


theme: jekyll-theme-slate
