# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Anubhav Singh"
subtitle: "See the world through experience!!"
author:  "Anubhav Singh"
header:
 title: "Photography"
 subtitle: "by Anubhav Singh"
footer:
 name: "Hey there, I am Anubhav Singh "
 bio: "I am a passionate iOS developer based in India. I used Swift as my primary language to make cool apps. I love to talk about new technologies and
the Apple ecosystem. "
social_urls:
  twitter: "https://twitter.com/anubhavpulkit"
  instagram: "https://www.instagram.com/soloe_xperience/"
  linkedin: "https://www.linkedin.com/in/anubhavpulkit"
  github: "https://github.com/anubhavpulkit"


theme: jekyll-theme-slate
